var requirejs,require,define;
(function(fa){function L(b){return"[object Function]"===R.call(b)}function M(b){return"[object Array]"===R.call(b)}function A(b,c){if(b){var e;for(e=0;e<b.length&&(!b[e]||!c(b[e],e,b));e+=1);}}function X(b,c){if(b){var e;for(e=b.length-1;-1<e&&(!b[e]||!c(b[e],e,b));--e);}}function y(b,c){return la.call(b,c)}function n(b,c){return y(b,c)&&b[c]}function G(b,c){for(var e in b)if(y(b,e)&&c(b[e],e))break}function Y(b,c,e,g){c&&G(c,function(c,h){if(e||!y(b,h))!g||"object"!==typeof c||!c||M(c)||L(c)||c instanceof
RegExp?b[h]=c:(b[h]||(b[h]={}),Y(b[h],c,e,g))});return b}function z(b,c){return function(){return c.apply(b,arguments)}}function ga(b){throw b;}function ha(b){if(!b)return b;var c=fa;A(b.split("."),function(b){c=c[b]});return c}function H(b,c,e,g){c=Error(c+"\nhttp://requirejs.org/docs/errors.html#"+b);c.requireType=b;c.requireModules=g;e&&(c.originalError=e);return c}function ma(b){function c(a,f,b){var d,p,l,c;f=f&&f.split("/");var e=m.map,g=e&&e["*"];if(a){a=a.split("/");var r=a.length-1;m.nodeIdCompat&&
S.test(a[r])&&(a[r]=a[r].replace(S,""));"."===a[0].charAt(0)&&f&&(r=f.slice(0,f.length-1),a=r.concat(a));r=a;for(d=0;d<r.length;d++)(p=r[d],"."===p)?(r.splice(d,1),--d):".."===p&&0!==d&&(1!==d||".."!==r[2])&&".."!==r[d-1]&&0<d&&(r.splice(d-1,2),d-=2);a=a.join("/")}if(b&&e&&(f||g)){r=a.split("/");d=r.length;a:for(;0<d;--d){var h=r.slice(0,d).join("/");if(f)for(p=f.length;0<p;--p)if(b=n(e,f.slice(0,p).join("/")))if(b=n(b,h)){var k=b;var q=d;break a}!l&&g&&n(g,h)&&(l=n(g,h),c=d)}!k&&l&&(k=l,q=c);k&&
(r.splice(0,q,k),a=r.join("/"))}return(k=n(m.pkgs,a))?k:a}function e(a){D&&A(document.getElementsByTagName("script"),function(f){if(f.getAttribute("data-requiremodule")===a&&f.getAttribute("data-requirecontext")===k.contextName)return f.parentNode.removeChild(f),!0})}function g(a){var f=n(m.paths,a);if(f&&M(f)&&1<f.length)return f.shift(),k.require.undef(a),k.makeRequire(null,{skipMap:!0})([a]),!0}function x(a){var f,b=a?a.indexOf("!"):-1;-1<b&&(f=a.substring(0,b),a=a.substring(b+1,a.length));return[f,
a]}function q(a,f,b,d){var p,l,e=null,g=f?f.name:null,h=a,r=!0,m="";a||(r=!1,a="_@r"+(R+=1));a=x(a);e=a[0];a=a[1];e&&(e=c(e,g,d),l=n(u,e));a&&(e?m=l&&l.normalize?l.normalize(a,function(a){return c(a,g,d)}):-1===a.indexOf("!")?c(a,g,d):a:(m=c(a,g,d),a=x(m),e=a[0],m=a[1],b=!0,p=k.nameToUrl(m)));b=!e||l||b?"":"_unnormalized"+(W+=1);return{prefix:e,name:m,parentMap:f,unnormalized:!!b,url:p,originalName:h,isDefine:r,id:(e?e+"!"+m:m)+b}}function v(a){var b=a.id,l=n(t,b);l||(l=t[b]=new k.Module(a));return l}
function w(a,b,l){var d=a.id,f=n(t,d);if(!y(u,d)||f&&!f.defineEmitComplete)if(f=v(a),f.error&&"error"===b)l(f.error);else f.on(b,l);else"defined"===b&&l(u[d])}function B(a,b){var f=a.requireModules,d=!1;if(b)b(a);else if(A(f,function(b){if(b=n(t,b))b.error=a,b.events.error&&(d=!0,b.emit("error",a))}),!d)h.onError(a)}function C(){T.length&&(oa.apply(E,[E.length,0].concat(T)),T=[])}function F(a){delete t[a];delete Z[a]}function K(a,b,l){var d=a.map.id;a.error?a.emit("error",a.error):(b[d]=!0,A(a.depMaps,
function(d,f){d=d.id;var c=n(t,d);c&&!a.depMatched[f]&&!l[d]&&(n(b,d)?(a.defineDep(f,u[d]),a.check()):K(c,b,l))}),l[d]=!0)}function I(){var a,b,c=(a=1E3*m.waitSeconds)&&k.startTime+a<(new Date).getTime(),d=[],p=[],h=!1,n=!0;if(!aa){aa=!0;G(Z,function(a){var f=a.map,l=f.id;if(a.enabled&&(f.isDefine||p.push(a),!a.error))if(!a.inited&&c)g(l)?h=b=!0:(d.push(l),e(l));else if(!a.inited&&a.fetched&&f.isDefine&&(h=!0,!f.prefix))return n=!1});if(c&&d.length)return a=H("timeout","Load timeout for modules: "+
d,null,d),a.contextName=k.contextName,B(a);n&&A(p,function(a){K(a,{},{})});c&&!b||!h||!D&&!ia||ba||(ba=setTimeout(function(){ba=0;I()},50));aa=!1}}function J(a){y(u,a[0])||v(q(a[0],null,!0)).init(a[1],a[2])}function N(a){a=a.currentTarget||a.srcElement;var b=k.onScriptLoad;a.detachEvent&&!ca?a.detachEvent("onreadystatechange",b):a.removeEventListener("load",b,!1);b=k.onScriptError;a.detachEvent&&!ca||a.removeEventListener("error",b,!1);return{node:a,id:a&&a.getAttribute("data-requiremodule")}}function O(){for(C();E.length;){var a=
E.shift();if(null===a[0])return B(H("mismatch","Mismatched anonymous define() module: "+a[a.length-1]));J(a)}}var aa,ba,m={waitSeconds:7,baseUrl:"./",paths:{},bundles:{},pkgs:{},shim:{},config:{}},t={},Z={},da={},E=[],u={},U={},ea={},R=1,W=1;var V={require:function(a){return a.require?a.require:a.require=k.makeRequire(a.map)},exports:function(a){a.usingExports=!0;if(a.map.isDefine)return a.exports?u[a.map.id]=a.exports:a.exports=u[a.map.id]={}},module:function(a){return a.module?a.module:a.module=
{id:a.map.id,uri:a.map.url,config:function(){return n(m.config,a.map.id)||{}},exports:a.exports||(a.exports={})}}};var ja=function(a){this.events=n(da,a.id)||{};this.map=a;this.shim=n(m.shim,a.id);this.depExports=[];this.depMaps=[];this.depMatched=[];this.pluginMaps={};this.depCount=0};ja.prototype={init:function(a,b,c,d){d=d||{};if(!this.inited){this.factory=b;if(c)this.on("error",c);else this.events.error&&(c=z(this,function(a){this.emit("error",a)}));this.depMaps=a&&a.slice(0);this.errback=c;this.inited=
!0;this.ignore=d.ignore;d.enabled||this.enabled?this.enable():this.check()}},defineDep:function(a,b){this.depMatched[a]||(this.depMatched[a]=!0,--this.depCount,this.depExports[a]=b)},fetch:function(){if(!this.fetched){this.fetched=!0;k.startTime=(new Date).getTime();var a=this.map;if(this.shim)k.makeRequire(this.map,{enableBuildCallback:!0})(this.shim.deps||[],z(this,function(){return a.prefix?this.callPlugin():this.load()}));else return a.prefix?this.callPlugin():this.load()}},load:function(){var a=
this.map.url;U[a]||(U[a]=!0,k.load(this.map.id,a))},check:function(){if(this.enabled&&!this.enabling){var a=this.map.id;var b=this.depExports;var c=this.exports,d=this.factory;if(this.inited)if(this.error)this.emit("error",this.error);else{if(!this.defining){this.defining=!0;if(1>this.depCount&&!this.defined){if(L(d)){if(this.events.error&&this.map.isDefine||h.onError!==ga)try{c=k.execCb(a,d,b,c)}catch(na){var p=na}else c=k.execCb(a,d,b,c);this.map.isDefine&&void 0===c&&((b=this.module)?c=b.exports:
this.usingExports&&(c=this.exports));if(p)return p.requireMap=this.map,p.requireModules=this.map.isDefine?[this.map.id]:null,p.requireType=this.map.isDefine?"define":"require",B(this.error=p)}else c=d;this.exports=c;if(this.map.isDefine&&!this.ignore&&(u[a]=c,h.onResourceLoad))h.onResourceLoad(k,this.map,this.depMaps);F(a);this.defined=!0}this.defining=!1;this.defined&&!this.defineEmitted&&(this.defineEmitted=!0,this.emit("defined",this.exports),this.defineEmitComplete=!0)}}else this.fetch()}},callPlugin:function(){var a=
this.map,b=a.id,e=q(a.prefix);this.depMaps.push(e);w(e,"defined",z(this,function(d){var f;var e=n(ea,this.map.id);var l=this.map.name,g=this.map.parentMap?this.map.parentMap.name:null,x=k.makeRequire(a.parentMap,{enableBuildCallback:!0});if(this.map.unnormalized){if(d.normalize&&(l=d.normalize(l,function(a){return c(a,g,!0)})||""),d=q(a.prefix+"!"+l,this.map.parentMap),w(d,"defined",z(this,function(a){this.init([],function(){return a},null,{enabled:!0,ignore:!0})})),e=n(t,d.id)){this.depMaps.push(d);
if(this.events.error)e.on("error",z(this,function(a){this.emit("error",a)}));e.enable()}}else e?(this.map.url=k.nameToUrl(e),this.load()):(f=z(this,function(a){this.init([],function(){return a},null,{enabled:!0})}),f.error=z(this,function(a){this.inited=!0;this.error=a;a.requireModules=[b];G(t,function(a){0===a.map.id.indexOf(b+"_unnormalized")&&F(a.map.id)});B(a)}),f.fromText=z(this,function(d,c){var e=a.name,p=q(e),l=P;c&&(d=c);l&&(P=!1);v(p);y(m.config,b)&&(m.config[e]=m.config[b]);try{h.exec(d)}catch(ka){return B(H("fromtexteval",
"fromText eval for "+b+" failed: "+ka,ka,[b]))}l&&(P=!0);this.depMaps.push(p);k.completeLoad(e);x([e],f)}),d.load(a.name,x,f,m))}));k.enable(e,this);this.pluginMaps[e.id]=e},enable:function(){Z[this.map.id]=this;this.enabling=this.enabled=!0;A(this.depMaps,z(this,function(a,b){var c;if("string"===typeof a){a=q(a,this.map.isDefine?this.map:this.map.parentMap,!1,!this.skipMap);this.depMaps[b]=a;if(c=n(V,a.id)){this.depExports[b]=c(this);return}this.depCount+=1;w(a,"defined",z(this,function(a){this.defineDep(b,
a);this.check()}));this.errback?w(a,"error",z(this,this.errback)):this.events.error&&w(a,"error",z(this,function(a){this.emit("error",a)}))}c=a.id;var d=t[c];!y(V,c)&&d&&!d.enabled&&k.enable(a,this)}));G(this.pluginMaps,z(this,function(a){var b=n(t,a.id);b&&!b.enabled&&k.enable(a,this)}));this.enabling=!1;this.check()},on:function(a,b){var c=this.events[a];c||(c=this.events[a]=[]);c.push(b)},emit:function(a,b){A(this.events[a],function(a){a(b)});"error"===a&&delete this.events[a]}};var k={config:m,
contextName:b,registry:t,defined:u,urlFetched:U,defQueue:E,Module:ja,makeModuleMap:q,nextTick:h.nextTick,onError:B,configure:function(a){a.baseUrl&&"/"!==a.baseUrl.charAt(a.baseUrl.length-1)&&(a.baseUrl+="/");var b=m.shim,c={paths:!0,bundles:!0,config:!0,map:!0};G(a,function(a,b){c[b]?(m[b]||(m[b]={}),Y(m[b],a,!0,!0)):m[b]=a});a.bundles&&G(a.bundles,function(a,b){A(a,function(a){a!==b&&(ea[a]=b)})});a.shim&&(G(a.shim,function(a,c){M(a)&&(a={deps:a});!a.exports&&!a.init||a.exportsFn||(a.exportsFn=
k.makeShimExports(a));b[c]=a}),m.shim=b);a.packages&&A(a.packages,function(a){a="string"===typeof a?{name:a}:a;var b=a.name;a.location&&(m.paths[b]=a.location);m.pkgs[b]=a.name+"/"+(a.main||"main").replace(pa,"").replace(S,"")});G(t,function(a,b){a.inited||a.map.unnormalized||(a.map=q(b))});(a.deps||a.callback)&&k.require(a.deps||[],a.callback)},makeShimExports:function(a){return function(){var b;a.init&&(b=a.init.apply(fa,arguments));return b||a.exports&&ha(a.exports)}},makeRequire:function(a,f){function g(d,
c,e){var l;f.enableBuildCallback&&c&&L(c)&&(c.__requireJsBuild=!0);if("string"===typeof d){if(L(c))return B(H("requireargs","Invalid require call"),e);if(a&&y(V,d))return V[d](t[a.id]);if(h.get)return h.get(k,d,a,g);var p=q(d,a,!1,!0);p=p.id;return y(u,p)?u[p]:B(H("notloaded",'Module name "'+p+'" has not been loaded yet for context: '+b+(a?"":". Use require([])")))}O();k.nextTick(function(){O();l=v(q(null,a));l.skipMap=f.skipMap;l.init(d,c,e,{enabled:!0});I()});return g}f=f||{};Y(g,{isBrowser:D,toUrl:function(b){var d=
b.lastIndexOf("."),e=b.split("/")[0];if(-1!==d&&("."!==e&&".."!==e||1<d)){var f=b.substring(d,b.length);b=b.substring(0,d)}return k.nameToUrl(c(b,a&&a.id,!0),f,!0)},defined:function(b){return y(u,q(b,a,!1,!0).id)},specified:function(b){b=q(b,a,!1,!0).id;return y(u,b)||y(t,b)}});a||(g.undef=function(b){C();var c=q(b,a,!0),d=n(t,b);e(b);delete u[b];delete U[c.url];delete da[b];X(E,function(a,c){a[0]===b&&E.splice(c,1)});d&&(d.events.defined&&(da[b]=d.events),F(b))});return g},enable:function(a){n(t,
a.id)&&v(a).enable()},completeLoad:function(a){var b=n(m.shim,a)||{},c=b.exports;for(C();E.length;){var d=E.shift();if(null===d[0]){d[0]=a;if(e)break;var e=!0}else d[0]===a&&(e=!0);J(d)}d=n(t,a);if(!e&&!y(u,a)&&d&&!d.inited){if(m.enforceDefine&&(!c||!ha(c)))return g(a)?void 0:B(H("nodefine","No define call for "+a,null,[a]));J([a,b.deps||[],b.exportsFn])}I()},nameToUrl:function(a,b,c){var d,e,f;(d=n(m.pkgs,a))&&(a=d);if(d=n(ea,a))return k.nameToUrl(d,b,c);if(h.jsExtRegExp.test(a))d=a+(b||"");else{d=
m.paths;a=a.split("/");for(e=a.length;0<e;--e)if(f=a.slice(0,e).join("/"),f=n(d,f)){M(f)&&(f=f[0]);a.splice(0,e,f);break}d=a.join("/");d+=b||(/^data\:|\?/.test(d)||c?"":".js");d=("/"===d.charAt(0)||d.match(/^[\w\+\.\-]+:/)?"":m.baseUrl)+d}return m.urlArgs?d+((-1===d.indexOf("?")?"?":"&")+m.urlArgs):d},load:function(a,b){h.load(k,a,b)},execCb:function(a,b,c,d){return b.apply(d,c)},onScriptLoad:function(a){if("load"===a.type||qa.test((a.currentTarget||a.srcElement).readyState))Q=null,a=N(a),k.completeLoad(a.id)},
onScriptError:function(a){var b=N(a);if(!g(b.id))return B(H("scripterror","Script error for: "+b.id,a,[b.id]))}};k.require=k.makeRequire();return k}var C,I,N,J,Q,O,v,W,ra=/(\/\*([\s\S]*?)\*\/|([^:]|^)\/\/(.*)$)/mg,sa=/[^.]\s*require\s*\(\s*["']([^'"\s]+)["']\s*\)/g,S=/\.js$/,pa=/^\.\//;var F=Object.prototype;var R=F.toString,la=F.hasOwnProperty,oa=Array.prototype.splice,D=!("undefined"===typeof window||"undefined"===typeof navigator||!window.document),ia=!D&&"undefined"!==typeof importScripts,qa=
D&&"PLAYSTATION 3"===navigator.platform?/^complete$/:/^(complete|loaded)$/,ca="undefined"!==typeof opera&&"[object Opera]"===opera.toString(),K={},w={},T=[],P=!1;if("undefined"===typeof define){if("undefined"!==typeof requirejs){if(L(requirejs))return;w=requirejs;requirejs=void 0}"undefined"!==typeof require&&!L(require)&&(w=require,require=void 0);var h=requirejs=function(b,c,e,g){var x,q="_";!M(b)&&"string"!==typeof b&&(x=b,M(c)?(b=c,c=e,e=g):b=[]);x&&x.context&&(q=x.context);(g=n(K,q))||(g=K[q]=
h.s.newContext(q));x&&g.configure(x);return g.require(b,c,e)};h.config=function(b){return h(b)};h.nextTick="undefined"!==typeof setTimeout?function(b){setTimeout(b,4)}:function(b){b()};require||(require=h);h.version="2.1.17";h.jsExtRegExp=/^\/|:|\?|\.js$/;h.isBrowser=D;F=h.s={contexts:K,newContext:ma};h({});A(["toUrl","undef","defined","specified"],function(b){h[b]=function(){var c=K._;return c.require[b].apply(c,arguments)}});D&&(C=F.head=document.getElementsByTagName("head")[0],I=document.getElementsByTagName("base")[0])&&
(C=F.head=I.parentNode);h.onError=ga;h.createNode=function(b){var c=b.xhtml?document.createElementNS("http://www.w3.org/1999/xhtml","html:script"):document.createElement("script");c.type=b.scriptType||"text/javascript";c.charset="utf-8";c.async=!0;return c};h.load=function(b,c,e){var g=b&&b.config||{};if(D)return g=h.createNode(g,c,e),g.setAttribute("data-requirecontext",b.contextName),g.setAttribute("data-requiremodule",c),!g.attachEvent||g.attachEvent.toString&&0>g.attachEvent.toString().indexOf("[native code")||
ca?(g.addEventListener("load",b.onScriptLoad,!1),g.addEventListener("error",b.onScriptError,!1)):(P=!0,g.attachEvent("onreadystatechange",b.onScriptLoad)),g.src=e,O=g,I?C.insertBefore(g,I):C.appendChild(g),O=null,g;if(ia)try{importScripts(e),b.completeLoad(c)}catch(x){b.onError(H("importscripts","importScripts failed for "+c+" at "+e,x,[c]))}};D&&!w.skipDataMain&&X(document.getElementsByTagName("script"),function(b){C||(C=b.parentNode);if(N=b.getAttribute("data-main"))return v=N,w.baseUrl||(J=v.split("/"),
v=J.pop(),W=J.length?J.join("/")+"/":"./",w.baseUrl=W),v=v.replace(S,""),h.jsExtRegExp.test(v)&&(v=N),w.deps=w.deps?w.deps.concat(v):[v],!0});define=function(b,c,e){var g,h;"string"!==typeof b&&(e=c,c=b,b=null);M(c)||(e=c,c=null);!c&&L(e)&&(c=[],e.length&&(e.toString().replace(ra,"").replace(sa,function(b,e){c.push(e)}),c=(1===e.length?["require"]:["require","exports","module"]).concat(c)));P&&((g=O)||(Q&&"interactive"===Q.readyState||X(document.getElementsByTagName("script"),function(b){if("interactive"===
b.readyState)return Q=b}),g=Q),g&&(b||(b=g.getAttribute("data-requiremodule")),h=K[g.getAttribute("data-requirecontext")]));(h?h.defQueue:T).push([b,c,e])};define.amd={jQuery:!0};h.exec=function(b){return eval(b)};h(w)}})(this);
